name: Continuous Integration v1

on:
  push:
    branches:
      - feature/**
      - feat/**
      - fix/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:ci

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  create-or-update-pr:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      - name: Obter Branch Atual
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          echo "A branch atual é: $CURRENT_BRANCH"

      - name: Atualizar ou criar Pull Request
        run: |
          if gh pr list | grep -q "$CURRENT_BRANCH"; then
            gh pr edit "$CURRENT_BRANCH" --body "Solicitação pull automática atualizada pelo GitHub Action."
          else
            gh pr create -B develop -H "$CURRENT_BRANCH" --title "Merge $CURRENT_BRANCH into develop" --body "Criado Pull Request automático pelo GitHub Action."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
