name: Continuos Integration v1

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:ci

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  create-pr:
    runs-on: ubuntu-latest
    needs: [lint, test, build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Obter Branch Atual
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          echo "A branch atual é: $CURRENT_BRANCH"

      - name: Create Pull Request
        run: gh pr create -B develop-teste -H feature/workflow-testes --title 'Merge feature/workflow-testes into develop-teste' --body 'Created automatic Pull Request by Github action.'
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
